### ISSUE TITLE
Nieprawidłowe użycie Typography

### ISSUE THREAD

**Issue by olcen-neoteric** [igorbacz/justjoin.it#7]
https://github.com/igorbacz/justjoin.it/blob/main/web/justjoin-it/src/components/searchBar/components/LocationMenu.tsx#L34

`<Typography>` służy do użycia stylu tekstu zapisanego w Theme. Nie ma użycia jako wrapper do reszty komponentów. Spróbuj to zastąpić odpowiednio ostylowanym Boxem

**Comment by igorbacz** [comment]
zrobione :)
