### ISSUE TITLE
Używanie tekstu

### ISSUE THREAD

**Issue by olcen-neoteric** [igorbacz/justjoin.it#8]
https://github.com/igorbacz/justjoin.it/blob/baa1d715319cb007d431277281000dfba25cd196/web/justjoin-it/src/components/searchBar/components/MoreFilters.tsx#L43

W każdym miejscu gdzie używasz tekstu, powinnaś skorzystać z Typography i podawać wariant :D Cały setting powinien być w głównym Theme

**Comment by igorbacz** [comment]
Zrobione :)
